@RestaurantAPI_HostAddress = http://localhost:5127

###
@restaurantId = 9

GET {{RestaurantAPI_HostAddress}}/api/restaurant/{{restaurantId}}


###
POST {{RestaurantAPI_HostAddress}}/api/restaurant
Content-Type: application/json
Authorization: Bearer {{token_admin1}}

{
  "name": "Pizza Amore",
  "description": "Rodzinna pizzeria oferująca włoską pizzę na cienkim cieście, działająca od 2005 roku.",
  "category": "Pizzeria",
  "hasDelivery": true,
  "contactEmail": "kontakt@pizzaamore.pl",
  "contactNumber": "+48 123 456 789",
  "city": "Kraków",
  "street": "Włoska 12",
  "postalCode": "31-100"
}


###
@deleteRestaurantId = 11

DELETE {{RestaurantAPI_HostAddress}}/api/restaurant/{{deleteRestaurantId}}


###
PUT {{RestaurantAPI_HostAddress}}/api/restaurant/{{restaurantId}}
Content-Type: application/json

{
  "name": "Pizza Amore",
  "description": "TEST",
  "hasDelivery": false
}

###
POST {{RestaurantAPI_HostAddress}}/api/restaurant/{{restaurantId}}/dish
Content-Type: application/json

{
  "name": "Margherita",
  "description": "Klasyczna pizza z mozzarellą i sosem pomidorowym",
  "price": 25.00
}

###
@dishId = 7

GET {{RestaurantAPI_HostAddress}}/api/restaurant/{{restaurantId}}/dish/{{dishId}}


###
GET {{RestaurantAPI_HostAddress}}/api/restaurant/{{restaurantId}}/dish


###
@deleteDishId = 9

DELETE {{RestaurantAPI_HostAddress}}/api/restaurant/{{restaurantId}}/dish/{{deleteDishId}}


###
DELETE {{RestaurantAPI_HostAddress}}/api/restaurant/{{restaurantId}}/dish


###
POST {{RestaurantAPI_HostAddress}}/api/account/register
Content-Type: application/json

{
  "email": "admin2@test.com",
  "password": "123456",
  "confirmPassword": "123456",
  "nationality": "Polish",
  "dateOfBirth": "2001-01-01"
}

###
POST {{RestaurantAPI_HostAddress}}/api/account/login
Content-Type: application/json

{
  "email": "admin1@test.com",
  "password": "123456"
}


###
@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0ZXN0QHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImV4cCI6MTc0OTAzNzU2MywiaXNzIjoiaHR0cDovL3Jlc3RhdXJhbnRhcGkuY29tIiwiYXVkIjoiaHR0cDovL3Jlc3RhdXJhbnRhcGkuY29tIn0.OejUT95yJAN_kR_5OaLgtjEWab0T88-Ongt9ReZQit8
@token_test1 = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0ZXN0MUB0ZXN0LmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJOYXRpb25hbGl0eSI6IlBvbGlzaCIsIkRhdGVPZkJpcnRoIjoiMDEuMDEuMjAwMSAwMDowMDowMCIsImV4cCI6MTc0OTAzOTkyMSwiaXNzIjoiaHR0cDovL3Jlc3RhdXJhbnRhcGkuY29tIiwiYXVkIjoiaHR0cDovL3Jlc3RhdXJhbnRhcGkuY29tIn0._-XoaToTGV-uv0c_P9RBMF_HpeGT0YnlL_KA_z6aB8M

@token_admin1 = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbjFAdGVzdC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsIk5hdGlvbmFsaXR5IjoiUG9saXNoIiwiRGF0ZU9mQmlydGgiOiIwMS4wMS4yMDAxIDAwOjAwOjAwIiwiZXhwIjoxNzQ5MDU2NDE5LCJpc3MiOiJodHRwOi8vcmVzdGF1cmFudGFwaS5jb20iLCJhdWQiOiJodHRwOi8vcmVzdGF1cmFudGFwaS5jb20ifQ.1MtY_EfqouN5eH9agzVoOSf37jCjd-Pl4-ado9hdjXw

GET {{RestaurantAPI_HostAddress}}/api/restaurant/?searchPhrase=k&pageSize=5&pageNumber=1&sortBy=Name&sortDirection=DESC
Accept: application/json
Authorization: Bearer {{token_admin1}}

###
GET {{RestaurantAPI_HostAddress}}/sample-file.txt


###
GET {{RestaurantAPI_HostAddress}}/file/?fileName=private-file.txt
Authorization: Bearer {{token}}

###
POST {{RestaurantAPI_HostAddress}}/file/?fileName=private-file.txt
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="sample-file.txt"
Content-Type: text/plain

< C:\Users\jdobr\Downloads\upload-file1.txt
--MyBoundary--
