@RestaurantAPI_HostAddress = http://localhost:5127

GET {{RestaurantAPI_HostAddress}}/api/restaurant/
Accept: application/json

###
GET {{RestaurantAPI_HostAddress}}/api/restaurant/9


###
POST {{RestaurantAPI_HostAddress}}/api/restaurant
Content-Type: application/json

{
  "name": "Pizza Amore",
  "description": "Rodzinna pizzeria oferująca włoską pizzę na cienkim cieście, działająca od 2005 roku.",
  "category": "Pizzeria",
  "hasDelivery": true,
  "contactEmail": "kontakt@pizzaamore.pl",
  "contactNumber": "+48 123 456 789",
  "city": "Kraków",
  "street": "Włoska 12",
  "postalCode": "31-100"
}


###
POST {{RestaurantAPI_HostAddress}}/api/restaurant
Content-Type: application/json

{
  "name": "Pizza Amoreafgsuyduahksydfakushgdfaksudhfasjhdfaskjdhfasjkdhfaskdjafhsda",
  "description": "Rodzinna pizzeria oferująca włoską pizzę na cienkim cieście, działająca od 2005 roku.",
  "category": "Pizzeria",
  "hasDelivery": true,
  "contactEmail": "kontakt@pizzaamore.pl",
  "contactNumber": "+48 123 456 789",
  "city": "Kraków jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
  "street": "Włoska 12 jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
  "postalCode": "31-100"
}


###
DELETE {{RestaurantAPI_HostAddress}}/api/restaurant/8



###
PUT {{RestaurantAPI_HostAddress}}/api/restaurant/9
Content-Type: application/json

{
  "name": "Pizza Amore",
  "description": "TEST",
  "hasDelivery": false
}